@echo off
echo Initializing Git repository...
git init
echo Adding files...
git add .
echo Committing files...
git commit -m "Initial commit: Add premium portfolio website"
echo Setting main branch...
git branch -M main
echo Adding remote...
git remote add origin https://github.com/thakurprithviraj452-spec/Portfolio.git
echo Pushing to GitHub...
git push -u origin main
echo.
echo Done! Press any key to exit.
pause
