@echo off
echo Committing files...
git add .
git commit -m "Update portfolio"
echo Setting main branch...
git branch -M main
echo Setting remote...
git remote set-url origin https://github.com/thakurprithviraj452-spec/Portfolio.git
echo Pushing to GitHub...
git push -u origin main
echo.
echo Done! Press any key to exit.
pause
